test

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -67,10 +67,10 @@ jobs:
               body: output
             })
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+            #- name: Terraform Plan Status
+            # if: steps.plan.outcome == 'failure'
+            #run: exit 1
 
       - name: Terraform Apply
-        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+        #if: github.ref == 'refs/heads/master' && github.event_name == 'push'
         run: terraform apply -auto-approve
